# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 赚赚

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    #- name: Install Pack
    #  run: npm install
        
    - name: 运行
      run: node jd_jdzz.js
      env:
        CI: true
        JD_COOKIE: ${{ secrets.JD_COOKIE_V }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
