# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  schedule:
    - cron: "3 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
#    - name: Install Pack
#      run: npm install

    - name: Read config from secrets  #读取机密
      env: 
        CONFIG_JD_COOKIE: ${{ secrets.CONFIG_JD_COOKIE }} # cookie1
        CONFIG_JD_COOKIE_V2: ${{ secrets.CONFIG_JD_COOKIE_V2 }} # cookie2
      run: |         
        echo $CONFIG_JD_COOKIE > config-cookie.txt
        echo $CONFIG_JD_COOKIE_V2 > config-cookie2.txt
        sed -i '21 r config-cookie.txt' jd.js
        sed -i '22 r config-cookie2.txt' jd.js
        
    - name: 进行签到
      run: node jd.js
      env:
        CI: true
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
